/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsS3RouteImport } from './routes/settings/s3'
import { Route as SettingsPromptsRouteImport } from './routes/settings/prompts'
import { Route as SettingsIntakeqTypesRouteImport } from './routes/settings/intakeq-types'
import { Route as SettingsIntakeqRouteImport } from './routes/settings/intakeq'
import { Route as SettingsEnvironmentRouteImport } from './routes/settings/environment'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsS3Route = SettingsS3RouteImport.update({
  id: '/settings/s3',
  path: '/settings/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPromptsRoute = SettingsPromptsRouteImport.update({
  id: '/settings/prompts',
  path: '/settings/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntakeqTypesRoute = SettingsIntakeqTypesRouteImport.update({
  id: '/settings/intakeq-types',
  path: '/settings/intakeq-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntakeqRoute = SettingsIntakeqRouteImport.update({
  id: '/settings/intakeq',
  path: '/settings/intakeq',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsEnvironmentRoute = SettingsEnvironmentRouteImport.update({
  id: '/settings/environment',
  path: '/settings/environment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/templates': typeof TemplatesRoute
  '/settings/environment': typeof SettingsEnvironmentRoute
  '/settings/intakeq': typeof SettingsIntakeqRoute
  '/settings/intakeq-types': typeof SettingsIntakeqTypesRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/s3': typeof SettingsS3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/templates': typeof TemplatesRoute
  '/settings/environment': typeof SettingsEnvironmentRoute
  '/settings/intakeq': typeof SettingsIntakeqRoute
  '/settings/intakeq-types': typeof SettingsIntakeqTypesRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/s3': typeof SettingsS3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/templates': typeof TemplatesRoute
  '/settings/environment': typeof SettingsEnvironmentRoute
  '/settings/intakeq': typeof SettingsIntakeqRoute
  '/settings/intakeq-types': typeof SettingsIntakeqTypesRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/settings/s3': typeof SettingsS3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/templates'
    | '/settings/environment'
    | '/settings/intakeq'
    | '/settings/intakeq-types'
    | '/settings/prompts'
    | '/settings/s3'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/templates'
    | '/settings/environment'
    | '/settings/intakeq'
    | '/settings/intakeq-types'
    | '/settings/prompts'
    | '/settings/s3'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/templates'
    | '/settings/environment'
    | '/settings/intakeq'
    | '/settings/intakeq-types'
    | '/settings/prompts'
    | '/settings/s3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  TemplatesRoute: typeof TemplatesRoute
  SettingsEnvironmentRoute: typeof SettingsEnvironmentRoute
  SettingsIntakeqRoute: typeof SettingsIntakeqRoute
  SettingsIntakeqTypesRoute: typeof SettingsIntakeqTypesRoute
  SettingsPromptsRoute: typeof SettingsPromptsRoute
  SettingsS3Route: typeof SettingsS3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/s3': {
      id: '/settings/s3'
      path: '/settings/s3'
      fullPath: '/settings/s3'
      preLoaderRoute: typeof SettingsS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/prompts': {
      id: '/settings/prompts'
      path: '/settings/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof SettingsPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/intakeq-types': {
      id: '/settings/intakeq-types'
      path: '/settings/intakeq-types'
      fullPath: '/settings/intakeq-types'
      preLoaderRoute: typeof SettingsIntakeqTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/intakeq': {
      id: '/settings/intakeq'
      path: '/settings/intakeq'
      fullPath: '/settings/intakeq'
      preLoaderRoute: typeof SettingsIntakeqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/environment': {
      id: '/settings/environment'
      path: '/settings/environment'
      fullPath: '/settings/environment'
      preLoaderRoute: typeof SettingsEnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  TemplatesRoute: TemplatesRoute,
  SettingsEnvironmentRoute: SettingsEnvironmentRoute,
  SettingsIntakeqRoute: SettingsIntakeqRoute,
  SettingsIntakeqTypesRoute: SettingsIntakeqTypesRoute,
  SettingsPromptsRoute: SettingsPromptsRoute,
  SettingsS3Route: SettingsS3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
