/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsS3RouteImport } from './routes/settings/s3'
import { Route as ApiTemplatesIndexRouteImport } from './routes/api/templates/index'
import { Route as ApiSessionsIndexRouteImport } from './routes/api/sessions/index'
import { Route as ApiS3CredentialsIndexRouteImport } from './routes/api/s3-credentials/index'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiGapsIndexRouteImport } from './routes/api/gaps/index'
import { Route as ApiAuditLogsIndexRouteImport } from './routes/api/audit-logs/index'
import { Route as ApiTemplatesIdRouteImport } from './routes/api/templates/$id'
import { Route as ApiSessionsHistoryRouteImport } from './routes/api/sessions/history'
import { Route as ApiNotesExportRouteImport } from './routes/api/notes/export'
import { Route as ApiNotesNoteIdRouteImport } from './routes/api/notes/$noteId'
import { Route as ApiGapsBatchRouteImport } from './routes/api/gaps/batch'
import { Route as ApiGapsIdRouteImport } from './routes/api/gaps/$id'
import { Route as ApiS3CredentialsUpdateIdRouteImport } from './routes/api/s3-credentials/update/$id'
import { Route as ApiS3CredentialsTestIdRouteImport } from './routes/api/s3-credentials/test/$id'
import { Route as ApiS3CredentialsDeleteIdRouteImport } from './routes/api/s3-credentials/delete/$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsS3Route = SettingsS3RouteImport.update({
  id: '/settings/s3',
  path: '/settings/s3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIndexRoute = ApiTemplatesIndexRouteImport.update({
  id: '/api/templates/',
  path: '/api/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsIndexRoute = ApiSessionsIndexRouteImport.update({
  id: '/api/sessions/',
  path: '/api/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3CredentialsIndexRoute = ApiS3CredentialsIndexRouteImport.update({
  id: '/api/s3-credentials/',
  path: '/api/s3-credentials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGapsIndexRoute = ApiGapsIndexRouteImport.update({
  id: '/api/gaps/',
  path: '/api/gaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditLogsIndexRoute = ApiAuditLogsIndexRouteImport.update({
  id: '/api/audit-logs/',
  path: '/api/audit-logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesIdRoute = ApiTemplatesIdRouteImport.update({
  id: '/api/templates/$id',
  path: '/api/templates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsHistoryRoute = ApiSessionsHistoryRouteImport.update({
  id: '/api/sessions/history',
  path: '/api/sessions/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesExportRoute = ApiNotesExportRouteImport.update({
  id: '/api/notes/export',
  path: '/api/notes/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesNoteIdRoute = ApiNotesNoteIdRouteImport.update({
  id: '/api/notes/$noteId',
  path: '/api/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGapsBatchRoute = ApiGapsBatchRouteImport.update({
  id: '/api/gaps/batch',
  path: '/api/gaps/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGapsIdRoute = ApiGapsIdRouteImport.update({
  id: '/api/gaps/$id',
  path: '/api/gaps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3CredentialsUpdateIdRoute =
  ApiS3CredentialsUpdateIdRouteImport.update({
    id: '/api/s3-credentials/update/$id',
    path: '/api/s3-credentials/update/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiS3CredentialsTestIdRoute = ApiS3CredentialsTestIdRouteImport.update({
  id: '/api/s3-credentials/test/$id',
  path: '/api/s3-credentials/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiS3CredentialsDeleteIdRoute =
  ApiS3CredentialsDeleteIdRouteImport.update({
    id: '/api/s3-credentials/delete/$id',
    path: '/api/s3-credentials/delete/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/templates': typeof TemplatesRoute
  '/settings/s3': typeof SettingsS3Route
  '/api/gaps/$id': typeof ApiGapsIdRoute
  '/api/gaps/batch': typeof ApiGapsBatchRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRoute
  '/api/notes/export': typeof ApiNotesExportRoute
  '/api/sessions/history': typeof ApiSessionsHistoryRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/api/audit-logs': typeof ApiAuditLogsIndexRoute
  '/api/gaps': typeof ApiGapsIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/s3-credentials': typeof ApiS3CredentialsIndexRoute
  '/api/sessions': typeof ApiSessionsIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/s3-credentials/delete/$id': typeof ApiS3CredentialsDeleteIdRoute
  '/api/s3-credentials/test/$id': typeof ApiS3CredentialsTestIdRoute
  '/api/s3-credentials/update/$id': typeof ApiS3CredentialsUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/templates': typeof TemplatesRoute
  '/settings/s3': typeof SettingsS3Route
  '/api/gaps/$id': typeof ApiGapsIdRoute
  '/api/gaps/batch': typeof ApiGapsBatchRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRoute
  '/api/notes/export': typeof ApiNotesExportRoute
  '/api/sessions/history': typeof ApiSessionsHistoryRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/api/audit-logs': typeof ApiAuditLogsIndexRoute
  '/api/gaps': typeof ApiGapsIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/s3-credentials': typeof ApiS3CredentialsIndexRoute
  '/api/sessions': typeof ApiSessionsIndexRoute
  '/api/templates': typeof ApiTemplatesIndexRoute
  '/api/s3-credentials/delete/$id': typeof ApiS3CredentialsDeleteIdRoute
  '/api/s3-credentials/test/$id': typeof ApiS3CredentialsTestIdRoute
  '/api/s3-credentials/update/$id': typeof ApiS3CredentialsUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/templates': typeof TemplatesRoute
  '/settings/s3': typeof SettingsS3Route
  '/api/gaps/$id': typeof ApiGapsIdRoute
  '/api/gaps/batch': typeof ApiGapsBatchRoute
  '/api/notes/$noteId': typeof ApiNotesNoteIdRoute
  '/api/notes/export': typeof ApiNotesExportRoute
  '/api/sessions/history': typeof ApiSessionsHistoryRoute
  '/api/templates/$id': typeof ApiTemplatesIdRoute
  '/api/audit-logs/': typeof ApiAuditLogsIndexRoute
  '/api/gaps/': typeof ApiGapsIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/s3-credentials/': typeof ApiS3CredentialsIndexRoute
  '/api/sessions/': typeof ApiSessionsIndexRoute
  '/api/templates/': typeof ApiTemplatesIndexRoute
  '/api/s3-credentials/delete/$id': typeof ApiS3CredentialsDeleteIdRoute
  '/api/s3-credentials/test/$id': typeof ApiS3CredentialsTestIdRoute
  '/api/s3-credentials/update/$id': typeof ApiS3CredentialsUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/templates'
    | '/settings/s3'
    | '/api/gaps/$id'
    | '/api/gaps/batch'
    | '/api/notes/$noteId'
    | '/api/notes/export'
    | '/api/sessions/history'
    | '/api/templates/$id'
    | '/api/audit-logs'
    | '/api/gaps'
    | '/api/notes'
    | '/api/s3-credentials'
    | '/api/sessions'
    | '/api/templates'
    | '/api/s3-credentials/delete/$id'
    | '/api/s3-credentials/test/$id'
    | '/api/s3-credentials/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/templates'
    | '/settings/s3'
    | '/api/gaps/$id'
    | '/api/gaps/batch'
    | '/api/notes/$noteId'
    | '/api/notes/export'
    | '/api/sessions/history'
    | '/api/templates/$id'
    | '/api/audit-logs'
    | '/api/gaps'
    | '/api/notes'
    | '/api/s3-credentials'
    | '/api/sessions'
    | '/api/templates'
    | '/api/s3-credentials/delete/$id'
    | '/api/s3-credentials/test/$id'
    | '/api/s3-credentials/update/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/templates'
    | '/settings/s3'
    | '/api/gaps/$id'
    | '/api/gaps/batch'
    | '/api/notes/$noteId'
    | '/api/notes/export'
    | '/api/sessions/history'
    | '/api/templates/$id'
    | '/api/audit-logs/'
    | '/api/gaps/'
    | '/api/notes/'
    | '/api/s3-credentials/'
    | '/api/sessions/'
    | '/api/templates/'
    | '/api/s3-credentials/delete/$id'
    | '/api/s3-credentials/test/$id'
    | '/api/s3-credentials/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  TemplatesRoute: typeof TemplatesRoute
  SettingsS3Route: typeof SettingsS3Route
  ApiGapsIdRoute: typeof ApiGapsIdRoute
  ApiGapsBatchRoute: typeof ApiGapsBatchRoute
  ApiNotesNoteIdRoute: typeof ApiNotesNoteIdRoute
  ApiNotesExportRoute: typeof ApiNotesExportRoute
  ApiSessionsHistoryRoute: typeof ApiSessionsHistoryRoute
  ApiTemplatesIdRoute: typeof ApiTemplatesIdRoute
  ApiAuditLogsIndexRoute: typeof ApiAuditLogsIndexRoute
  ApiGapsIndexRoute: typeof ApiGapsIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiS3CredentialsIndexRoute: typeof ApiS3CredentialsIndexRoute
  ApiSessionsIndexRoute: typeof ApiSessionsIndexRoute
  ApiTemplatesIndexRoute: typeof ApiTemplatesIndexRoute
  ApiS3CredentialsDeleteIdRoute: typeof ApiS3CredentialsDeleteIdRoute
  ApiS3CredentialsTestIdRoute: typeof ApiS3CredentialsTestIdRoute
  ApiS3CredentialsUpdateIdRoute: typeof ApiS3CredentialsUpdateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/s3': {
      id: '/settings/s3'
      path: '/settings/s3'
      fullPath: '/settings/s3'
      preLoaderRoute: typeof SettingsS3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/': {
      id: '/api/templates/'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/': {
      id: '/api/sessions/'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3-credentials/': {
      id: '/api/s3-credentials/'
      path: '/api/s3-credentials'
      fullPath: '/api/s3-credentials'
      preLoaderRoute: typeof ApiS3CredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gaps/': {
      id: '/api/gaps/'
      path: '/api/gaps'
      fullPath: '/api/gaps'
      preLoaderRoute: typeof ApiGapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit-logs/': {
      id: '/api/audit-logs/'
      path: '/api/audit-logs'
      fullPath: '/api/audit-logs'
      preLoaderRoute: typeof ApiAuditLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates/$id': {
      id: '/api/templates/$id'
      path: '/api/templates/$id'
      fullPath: '/api/templates/$id'
      preLoaderRoute: typeof ApiTemplatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/history': {
      id: '/api/sessions/history'
      path: '/api/sessions/history'
      fullPath: '/api/sessions/history'
      preLoaderRoute: typeof ApiSessionsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/export': {
      id: '/api/notes/export'
      path: '/api/notes/export'
      fullPath: '/api/notes/export'
      preLoaderRoute: typeof ApiNotesExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$noteId': {
      id: '/api/notes/$noteId'
      path: '/api/notes/$noteId'
      fullPath: '/api/notes/$noteId'
      preLoaderRoute: typeof ApiNotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gaps/batch': {
      id: '/api/gaps/batch'
      path: '/api/gaps/batch'
      fullPath: '/api/gaps/batch'
      preLoaderRoute: typeof ApiGapsBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gaps/$id': {
      id: '/api/gaps/$id'
      path: '/api/gaps/$id'
      fullPath: '/api/gaps/$id'
      preLoaderRoute: typeof ApiGapsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3-credentials/update/$id': {
      id: '/api/s3-credentials/update/$id'
      path: '/api/s3-credentials/update/$id'
      fullPath: '/api/s3-credentials/update/$id'
      preLoaderRoute: typeof ApiS3CredentialsUpdateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3-credentials/test/$id': {
      id: '/api/s3-credentials/test/$id'
      path: '/api/s3-credentials/test/$id'
      fullPath: '/api/s3-credentials/test/$id'
      preLoaderRoute: typeof ApiS3CredentialsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/s3-credentials/delete/$id': {
      id: '/api/s3-credentials/delete/$id'
      path: '/api/s3-credentials/delete/$id'
      fullPath: '/api/s3-credentials/delete/$id'
      preLoaderRoute: typeof ApiS3CredentialsDeleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  TemplatesRoute: TemplatesRoute,
  SettingsS3Route: SettingsS3Route,
  ApiGapsIdRoute: ApiGapsIdRoute,
  ApiGapsBatchRoute: ApiGapsBatchRoute,
  ApiNotesNoteIdRoute: ApiNotesNoteIdRoute,
  ApiNotesExportRoute: ApiNotesExportRoute,
  ApiSessionsHistoryRoute: ApiSessionsHistoryRoute,
  ApiTemplatesIdRoute: ApiTemplatesIdRoute,
  ApiAuditLogsIndexRoute: ApiAuditLogsIndexRoute,
  ApiGapsIndexRoute: ApiGapsIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiS3CredentialsIndexRoute: ApiS3CredentialsIndexRoute,
  ApiSessionsIndexRoute: ApiSessionsIndexRoute,
  ApiTemplatesIndexRoute: ApiTemplatesIndexRoute,
  ApiS3CredentialsDeleteIdRoute: ApiS3CredentialsDeleteIdRoute,
  ApiS3CredentialsTestIdRoute: ApiS3CredentialsTestIdRoute,
  ApiS3CredentialsUpdateIdRoute: ApiS3CredentialsUpdateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
